gui.tab("Aimbot", "B")
gui.subtab("General")
gui.checkbox("Jumpscout")
gui.options(gui.checkbox("Hitbox override"), function ()
    local hp_condition = gui.checkbox("HP condition")
    gui.checkbox("HP condition 2"):master(hp_condition)
    gui.checkbox("HP condition 3"):master(hp_condition)
    gui.checkbox("HP condition 4"):master(hp_condition)
    gui.checkbox("HP condition 5"):master(hp_condition)
    gui.checkbox("HP condition 6")
end)
gui.column()
gui.checkbox("HP conditions")

gui.subtab("Exploits")
gui.checkbox("Ideal tick")
gui.checkbox("Improve speed")
gui.checkbox("Auto teleport")
gui.subtab("Misc")
gui.tab("Anti-Aim", "C")
gui.subtab("General")
gui.subtab("Builder")
gui.tab("Visuals", "D")
gui.subtab("Players")
gui.subtab("World")
gui.subtab("Local")
gui.subtab("Widgets")
gui.subtab("Misc")

gui.tab("Misc", "E")
gui.subtab("General")