gui.tab("Aimbot", "B")
gui.subtab("General")
gui.checkbox("Jumpscout")
gui.checkbox("Hitbox override")
gui.checkbox("HP conditions")
gui.subtab("Exploits")
gui.checkbox("Ideal tick")
gui.checkbox("Improve speed")
gui.checkbox("Auto teleport")
gui.subtab("Misc")
gui.tab("Anti-Aim", "C")
gui.subtab("General")
gui.subtab("Builder")
gui.tab("Visuals", "D")
gui.subtab("Players")
gui.subtab("World")
gui.subtab("Local")
gui.subtab("Widgets")
gui.subtab("Misc")

gui.tab("Misc", "E")
gui.subtab("General")