local gui = require("includes.gui")
gui.tab("Aimbot", "B")
gui.subtab("General")
gui.subtab("Exploits")
gui.subtab("Misc")
gui.tab("Anti-Aim", "C")
gui.subtab("General")
gui.subtab("Builder")
gui.tab("Visuals", "D")
gui.subtab("Players")
gui.subtab("World")
gui.subtab("Local")
gui.subtab("Widgets")
gui.subtab("Misc")

gui.tab("Misc", "E")
gui.subtab("General")